# Generated by Django 3.1 on 2021-03-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_handled', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('home_address', models.CharField(blank=True, max_length=300, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True)),
                ('age_class', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_centres', to='accounts.healthcentre')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_immunized', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('site_given', models.CharField(blank=True, choices=[('L', 'Left Arm'), ('R', 'Right Arm')], max_length=12, null=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_centres', to='accounts.healthcentre')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('B', 'Birth'), ('6w', '6 weeks (Infants)'), ('10w', '10 weeks (Infants)'), ('14w', '14 weeks (Infants)'), ('6m', '6 moonths (Infants)'), ('9m', '9 months (Infants)'), ('12m', '12-24 months (Infants)'), ('15m', '15-18 months (Infants)'), ('24m', '24 months (Infants)'), ('L', 'Less than 13 years ')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('imu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imus', to='records.immunogen')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=30)),
                ('schedule_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_done', to='records.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='vaccine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='records.vaccine'),
        ),
        migrations.CreateModel(
            name='RecordView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
